import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "reflect-metadata";
import { getDictionary } from "@/util/getDictionary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: any;
}) {
	// const dictionary = await getDictionary(params.lang)
	return (
		<html lang={params.lang}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
